version: '3.5'

services:
  database:
    container_name: database
    image: postgres
    ports:
      - "5555:5432"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - shared:/var/lib/postgresql/data
volumes:
  shared:
