name: Linting

on:
  push

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install turbo
        run: npm install turbo --global

      - name: Run lint
        run: turbo lint

      - name: "Create .netrc for Heroku Auth"
        shell: bash
        run: |
          `cat >~/.netrc <<EOF
          machine api.heroku.com
              login $EMAIL
              password $HEROKU_AUTH_TOKEN
          machine git.heroku.com
              login $EMAIL
              password $HEROKU_AUTH_TOKEN
          EOF`
        env:
          EMAIL: ${{secrets.HEROKU_DEPLOY_EMAIL}}
          HEROKU_AUTH_TOKEN: ${{secrets.HEROKU_API_KEY}}

      - name: "Add remote"
        shell: "bash"
        run: |
          heroku git:remote --app gmn-test
      
      - name: "Push to heroku"
        shell: "bash"
        run: |
          git push heroku HEAD:main

      
