name: Linting

on:
  push

env:
  CI: true

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install turbo
        run: npm install -g turbo

      # - name: Run lint
      #   run: turbo lint

      - uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "guide-me-now30"
          heroku_email: ${{secrets.HEROKU_DEPLOY_EMAIL}}
          procfile: "web: turbo build --filter=server && cd apps/server && pnpm run start:prod"
          region: eu
          # rollbackonhealthcheckfailed: true
          buildpack: https://github.com/unfold/heroku-buildpack-pnpm
        env:
          HD_DATABASE_URL: ${{secrets.DATABASE_URL}}
          HD_JWT_SECRET: ${{secrets.JWT_SECRET}}
          HD_SERVER_END: true
          # HD_MAILGUN_API_KEY: ${{secrets.MAILGUN_API_KEY}}

      # - name: "Create .netrc for Heroku Auth"
      #   shell: bash
      #   run: |
      #     `cat >~/.netrc <<EOF
      #     machine api.heroku.com
      #         login $EMAIL
      #         password $HEROKU_AUTH_TOKEN
      #     machine git.heroku.com
      #         login $EMAIL
      #         password $HEROKU_AUTH_TOKEN
      #     EOF`
      #   env:
      #     EMAIL: ${{secrets.HEROKU_DEPLOY_EMAIL}}
      #     HEROKU_AUTH_TOKEN: ${{secrets.HEROKU_API_KEY}}

      # - name: "Add remote"
      #   shell: "bash"
      #   run: |
      #     heroku git:remote --app gmn-test
      
      # - name: "Push to heroku"
      #   shell: "bash"
      #   run: |
      #     git push heroku HEAD:main
      #   env:
      #     RUST_BACKTRACE: 1

      
