name: Deploy

on:
  push:
    branches:
      - dev

env:
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install global
        run: npm install turbo --global && npm install pnpm --global

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: turbo build --filter=server
        

      - uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "guide-me-now"
          heroku_email: ${{secrets.HEROKU_DEPLOY_EMAIL}}
          branch: "dev"
          procfile: "web: cd apps/server && pnpm run start"