name: Deploy

on:
  push:
    branches:
      - dev

env:
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  MAILGUN_API_KEY: ${{secrets.MAILGUN_API_KEY}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --all --unshallow

      - name: Install global
        run: npm install turbo --global && npm install pnpm --global

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: turbo build
      
      - uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "guide-me-now26"
          heroku_email: ${{secrets.HEROKU_DEPLOY_EMAIL}}
          procfile: "web: cd apps/server && pnpm run start"
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          MAILGUN_API_KEY: ${{secrets.MAILGUN_API_KEY}}

