name: Lint & deploy

on:
  push:
    branches:
      - dev

env:
  CI: true

jobs:
  main:
    name: Lint & deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.8]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install turbo
        run: npm install -g turbo

      - name: Run lint
        run: turbo lint

      - name: Deploy server
        uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "aially-server-production"
          heroku_email: ${{secrets.HEROKU_DEPLOY_EMAIL}}
          procfile: "web: cd apps/server && pnpm run start:prod"
          region: eu
          rollbackonhealthcheckfailed: true
          buildpack: https://github.com/unfold/heroku-buildpack-pnpm
        env:
          HD_DATABASE_URL: ${{secrets.DATABASE_URL}}
          HD_JWT_SECRET: ${{secrets.JWT_SECRET}}
          HD_CLIENT_URL: https://aially-client-production.herokuapp.com
          # HD_MAILGUN_API_KEY: ${{secrets.MAILGUN_API_KEY}}
          HD_NODE_MODULES_CACHE: false
          HD_USE_YARN_CACHE: false

      - name: Deploy client
        uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "aially-client-production"
          heroku_email: ${{secrets.HEROKU_DEPLOY_EMAIL}}
          procfile: "web: cd apps/client && pnpm run start"
          region: eu
          rollbackonhealthcheckfailed: true
          buildpack: https://github.com/unfold/heroku-buildpack-pnpm
        env:
          HD_APP_PUBLIC_URL: https://aially-client-production.herokuapp.com
          HD_NEXT_PUBLIC_API_URL: https://aially-server-production.herokuapp.com/graphql
          HD_NODE_MODULES_CACHE: false
          HD_USE_YARN_CACHE: false
