name: Deploy

on:
  push:
    branches:
      - dev

env:
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  MAILGUN_API_KEY: ${{secrets.MAILGUN_API_KEY}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install global
        run: npm install turbo --global && npm install pnpm --global

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: turbo build --filter=server
      
      - uses: akhileshns/heroku-deploy@v3.7.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "guide-me-now21"
          heroku_email: ${{secrets.HEROKU_DEPLOY_EMAIL}}
          branch: "dev"
          procfile: "web: cd apps/server && pnpm run start"
          buildpack: "https://github.com/unfold/heroku-buildpack-pnpm"
          dontuseforce: true
          usedocker: true
          docker_build_args: |
            DATABASE_URL
            JWT_SECRET
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          MAILGUN_API_KEY: ${{secrets.MAILGUN_API_KEY}}

